### ISSUE TITLE
Bigger VRAM footprint after update?

### ISSUE THREAD

**Issue by Xabab** [PygmalionAI/aphrodite-engine#188]
Enviroment is Google Colab, Tesla T4, either with CUDA 12.1 or downgraded 11.8

aphrodite-engine==0.4.2 runs 13B GPTQ models without an issue, but after updating to 0.4.5 it consistently crashes with torch.cuda.OutOfMemoryError

**Comment by AlpinDale** [comment]
Try increasing the memory utilization, since the new release can handle much larger values (up to 1.0 if there's no idle vram usage). This doesn't apply to GPTQ, but CUDA graphs are enabled by default and they use about 2gb extra vram, you can disable them with --enforce-eager or enforce_eager=True if using in a script.

**Comment by Xabab** [comment]
Nope, still crashes with OOM
Full command:
```
python -m aphrodite.endpoints.openai.api_server \
--download-dir ./models \
--model "TheBloke/MythoMax-L2-13B-AWQ" \
--gpu-memory-utilization 1 \
--swap-space 5 \
--api-keys key \
--dtype float16 \
--enforce-eager \
--host 127.0.0.1 \
--port 5000 \
--max-model-len 4096
```

**Comment by Xabab** [comment]
nvm, that's me being dumb. I forgot to add --quantization gptq/awq, aphrodite-engine 0.4.2 managed to load gptq models even w/o it
