### ISSUE TITLE
Request: Support CLI option for concurrent request rate limit

### ISSUE THREAD

**Issue by sandwichdoge** [PygmalionAI/aphrodite-engine#92]
Hi,
We need this in order to prevent OOM. I see the API already supports this but a CLI option would be good.
Thank you.

**Comment by g4rg** [comment]
If you get OOM you might need to adjust `--gpu-memory-utilization` because requests that don't fit should get queued up internally already.
That said, I'm also in favor of such an option to improve possible backpressure handling.

**Comment by AlpinDale** [comment]
> If you get OOM you might need to adjust `--gpu-memory-utilization` because requests that don't fit should get queued up internally already. That said, I'm also in favor of such an option to improve possible backpressure handling.

They are queued, yes, but too many concurrent requests tend to fill up the GPU KV cache quickly and lead to OOMs regardless. If we have an option for limiting concurrent requests on the API level, we can run extensive benchmarks to determine the maximum number of requests for each model/GPU. The numbers reported in the README, for example, are the maximum number of requests per second I could send before OOM. The real numbers are slightly lower, I guess, because not all of the requests filled up the context window + request 512 tokens of output.

**Comment by AlpinDale** [comment]
The option `--max-num-seqs` should handle this. It's set to 256 by default.
